# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageMon.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QApplication

from stream import VideoWindow
class Ui_MainWindow2(object):
    def livestream(self):
        self.player = VideoWindow()
        self.player.resize(1078, 632)
        self.player.show()


    
    def confirmation(self):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText("Would you like to change the label of this image?")
        msgBox.setWindowTitle("Confirmation Message")
        msgBox.setStandardButtons(QMessageBox.Yes | QMessageBox.No)

        returnValue = msgBox.exec()
        if returnValue == QMessageBox.Yes:
            self.label.setStyleSheet("border: 5px solid green")

    def confirmation2(self):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText("Would you like to change the label of this image?")
        msgBox.setWindowTitle("Confirmation Message")
        msgBox.setStandardButtons(QMessageBox.Yes | QMessageBox.No)

        returnValue = msgBox.exec()
        if returnValue == QMessageBox.Yes:
            self.label_2.setStyleSheet("border: 5px solid green")
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1178, 632)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(57, 57, 57);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 110, 241, 221))
        self.label.setStyleSheet("border: 5px solid red")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(5)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images (1).jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 110, 241, 221))
        self.label_2.setStyleSheet("border: 5px solid green")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(5)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images (2).jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 110, 241, 221))
        self.label_3.setStyleSheet("border: 5px solid green")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(5)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("mon2.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 370, 241, 221))
        self.label_5.setStyleSheet("border: 5px solid green")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setLineWidth(5)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("mon4.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(610, 370, 241, 221))
        self.label_6.setStyleSheet("border: 5px solid green")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setLineWidth(5)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("mon5.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 370, 241, 221))
        self.label_8.setStyleSheet("border: 5px solid red")
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setLineWidth(5)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("mon7.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 40, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(81, 81, 81);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.livestream)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1040, 40, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(81, 81, 81);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setEnabled(False)
        self.dateTimeEdit.setGeometry(QtCore.QRect(790, 10, 194, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setStyleSheet("background-color: rgb(53, 53, 53);\n"
"color: rgb(255, 255, 255);")
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 2, 22), QtCore.QTime(17, 30, 48)))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(240, 120, 41, 31))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("change.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(55, 55))
        self.toolButton.setObjectName("toolButton")
        self.toolButton.clicked.connect(self.confirmation)
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(520, 120, 41, 31))
        self.toolButton_2.setText("")
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setIconSize(QtCore.QSize(55, 55))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_2.clicked.connect(self.confirmation2)
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(800, 120, 41, 31))
        self.toolButton_3.setText("")
        self.toolButton_3.setIcon(icon)
        self.toolButton_3.setIconSize(QtCore.QSize(55, 55))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setGeometry(QtCore.QRect(240, 380, 41, 31))
        self.toolButton_4.setText("")
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setIconSize(QtCore.QSize(55, 55))
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_5.setGeometry(QtCore.QRect(520, 380, 41, 31))
        self.toolButton_5.setText("")
        self.toolButton_5.setIcon(icon)
        self.toolButton_5.setIconSize(QtCore.QSize(55, 55))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_6.setGeometry(QtCore.QRect(800, 380, 41, 31))
        self.toolButton_6.setText("")
        self.toolButton_6.setIcon(icon)
        self.toolButton_6.setIconSize(QtCore.QSize(55, 55))
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_8 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_8.setGeometry(QtCore.QRect(1080, 380, 41, 31))
        self.toolButton_8.setText("")
        self.toolButton_8.setIcon(icon)
        self.toolButton_8.setIconSize(QtCore.QSize(55, 55))
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_7 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_7.setGeometry(QtCore.QRect(1080, 120, 41, 31))
        self.toolButton_7.setText("")
        self.toolButton_7.setIcon(icon)
        self.toolButton_7.setIconSize(QtCore.QSize(55, 55))
        self.toolButton_7.setObjectName("toolButton_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(890, 110, 241, 221))
        self.label_7.setStyleSheet("border: 5px solid green")
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setLineWidth(5)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("mon6.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.toolButton_10 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_10.setGeometry(QtCore.QRect(1080, 380, 41, 31))
        self.toolButton_10.setText("")
        self.toolButton_10.setIcon(icon)
        self.toolButton_10.setIconSize(QtCore.QSize(55, 55))
        self.toolButton_10.setObjectName("toolButton_10")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(890, 370, 241, 221))
        self.label_10.setStyleSheet("border: 5px solid red")
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setLineWidth(5)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("mon8.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.pushButton.raise_()
        self.dateTimeEdit.raise_()
        self.toolButton.raise_()
        self.toolButton_2.raise_()
        self.toolButton_3.raise_()
        self.toolButton_4.raise_()
        self.toolButton_5.raise_()
        self.toolButton_6.raise_()
        self.label_7.raise_()
        self.toolButton_10.raise_()
        self.label_10.raise_()
        self.toolButton_8.raise_()
        self.toolButton_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Play Live Stream"))
        self.pushButton_2.setText(_translate("MainWindow", "SignOut"))
       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
